# Generated by Django 4.1.3 on 2023-03-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='Location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
